name: august_chat
description: "Wallabie Chat project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  
  uuid: ^4.5.2
  bloc: ^9.0.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7

  firebase_core: ^3.15.2  
  firebase_auth: ^5.7.0
  firebase_ui_auth: ^2.0.0  
  firebase_ui_oauth_google: ^1.4.3
  flutter_localizations:
    sdk: flutter
  firebase_ui_localizations: ^1.14.1
  
  google_sign_in: ^6.1.1
  cloud_firestore: ^5.6.12

  flutter_chat_ui: ^2.11.1
  flutter_chat_core: ^2.9.0
  flutter_chat_types: ^3.6.2
  flutter_firebase_chat_core: ^1.6.8
  flutter_bloc: ^9.1.1
  emoji_picker_flutter: ^4.4.0
  google_fonts: ^7.0.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  flow_builder: ^0.1.0
  intl: any
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0  

  bloc_lint: ^0.3.2
  build_runner: ^2.10.1
  json_serializable: ^6.11.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
